### ISSUE TITLE
Interpreting output of TCI function

### ISSUE THREAD

**Issue by philip-ad** [jarretrt/tci#1]
Dear Ryan
Firstly thank you for the TCI package. I suspect it is exactly what I need for my own work and thank you for putting in all the hard work.
I am bit stuck.
The output to the TCI model gives the column 'infrt'. Is this the rate of the infusion during that time period? If so what units is it in? I have tried with Snieder and with Eleveld (PK plasma targeting only, both paediatric and adult). As mg/hour looks wrong (way to low) but not sure works for any other units I can think of.

If this column is not the infusion rate is this given?

I included below.
`
patient_dat_sn <- data.frame(AGE  = c(40),
                          TBM  = c(60),
                          HGT  = c(180),
                          MALE = c(TRUE))

patient_pk_sn <- schnider_poppk(patient_dat_sn, rand = FALSE, rate = FALSE)

patient_pk_sn

tci_targets <- c(6,6)
tci_times <- c(0,10)

tci_patient_sn <- tci(Ct = tci_targets, 
                    tms = tci_times, 
                    pkmod = pkmod3cpt, 
                    pars = patient_pk_sn, 
                    tci_alg = "plasma")

tci_patient_sn 

tci_sn <- predict_pkmod(pkmod3cpt, 
              pars =  patient_pk_1_sn,
              inf = tci_patient1_sn, 
              tms = c(1,2,8))

tci_sn`
Best wishes 

Phil Arnold

**Comment by philip-ad** [comment]
OK. Mg/minute makes sense. Thanks again

**Comment by jarretrt** [comment]
Hi Phil, 

Sorry for the slow response and I'm glad that you worked it out. 

You're correct that the column "infrt" is the rate (amount/time) for the duration of the infusion (dtm). The specific units will depend on the model being used and will need to be consistent with the units of the model parameters. If elimination/clearance parameters are in terms of minutes, as for the Schnider and Eleveld models, then dtm will also be in terms of minutes. 

The units of the amount can be inferred by looking at the units of the concentrations and the units of the volume parameter. Both Schnider and Eleveld models report concentrations in micrograms per milliliter, which are equivalent to milligrams per liter. Since the central volume parameters are in in liters, the units of mass must be milligrams.

One more quick note regarding the infusion units: the infusion rates are provided in units of mass per time because that's how the inputs to the PK system are defined. In practice, however, TCI pumps used for anesthesia may have upper bounds in terms of volume per time (e.g., 1200 ml/h). To ensure that the TCI algorithm doesn't return values that are incompatible with a specific pump and solution concentration, you may have to adjust the "maxrt" parameter in "tci_plasma" or "tci_effect". 

Propofol is usually given in a 10 mg/ml solution, so the upper bound would be

1,200 ml/h = 12,000 mg/h = 200 mg/min

All that said, you could, in theory, increase the solution concentration to achieve a higher limit. 

I hope this helps and I'm happy to hear the package is of use to you! 

Best,
Ryan
